apiVersion: v2
appVersion: "1.0"
dependencies:
- name: starburst-charts-common
  repository: https://github.service.anz/prex/service-starburst/starburst-charts-common/helm
  version: 380.0.0
description: A Helm chart for Starburst Enterprise
name: starburst-enterprise
version: 380.0.0
