# ------------------------------------------------------------------------------
# Coordinator Configuration
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: values-yaml-secret
  labels:
    name: values-yaml-secret
data:
  values.yaml: {{ tpl (toYaml .Values) $ | b64enc }}
