{{- if .Values.externalSecrets.enabled -}}
{{- if eq .Values.externalSecrets.type "goDaddy" -}}
{{- $helperFunctionResolvePipeline := dict -}}
{{- $_ := set $helperFunctionResolvePipeline "coordinatorEtcFiles" .Values.coordinator.etcFiles -}}
{{- $_ := set $helperFunctionResolvePipeline "coordinatorAdditionalProperties" .Values.coordinator.additionalProperties -}}
{{- $_ := set $helperFunctionResolvePipeline "workerEtcFiles" .Values.worker.etcFiles -}}
{{- $_ := set $helperFunctionResolvePipeline "workerAdditionalProperties" .Values.worker.additionalProperties -}}
{{- $_ := set $helperFunctionResolvePipeline "catalogs" .Values.catalogs -}}
{{- $arguments := dict -}}
{{- $_ := set $arguments "helperFunctionResolvePipeline" $helperFunctionResolvePipeline -}}
{{- $_ := set $arguments "helperFunctionTemplate" (.Files.Get "files/godaddy-external-secret.tpl") -}}
{{- $_ := set $arguments "secretPrefix" .Values.externalSecrets.secretPrefix -}}
{{- $_ := set $arguments "backendType" .Values.externalSecrets.goDaddy.backendType -}}
{{- $_ := set $arguments "helperFunctionName" "secretRef" -}}
{{ include "helperFunction.renderer" (dict "Values" $arguments "Template" $.Template) }}
{{- $_ := set $arguments "helperFunctionName" "secretEnv" -}}
{{ include "helperFunction.renderer" (dict "Values" $arguments "Template" $.Template) }}
{{ end -}}
{{- end }}
