{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.coordinator.service.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    role: prometheus-coordinator
spec:
  selector:
    {{- include "app.labels" . | nindent 4 }}
    role: coordinator
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.prometheus.agent.port }}
  type: ClusterIP
{{- end }}
