{{- if .Values.worker.kedaScaler.enabled }}
{{- if .Values.worker.autoscaling.enabled }}
{{- fail (printf "\n!!! You cannot use .Values.worker.kedaScaler.enabled and .Values.worker.autoscaling.enabled at the same time") -}}
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-sep-scaler
spec:
  {{- $scalerAddress := print "keda-sep-scaler." .Release.Namespace ".svc.cluster.local:" .Values.worker.kedaScaler.port }}
  {{- range $index, $trigger := .Values.worker.kedaScaler.scaledObjectSpec.triggers }}
    {{- if not (get $trigger.metadata "scalerAddress") }}
      {{- $_ := set $trigger.metadata "scalerAddress" $scalerAddress }}
    {{- end }}
  {{- end }}
  {{- toYaml .Values.worker.kedaScaler.scaledObjectSpec | nindent 2 }}
{{- end }}
