{{- if .Values.worker.kedaScaler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: keda-sep-scaler
  labels:
    {{- include "app.labels" . | nindent 4 }}
    role: keda-sep-scaler
    headless: "true"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.worker.kedaScaler.port }}
      protocol: TCP
  selector:
    {{- include "app.labels" . | nindent 4 }}
    role: coordinator
{{- end }}
